apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: higress-gateway
  namespace: higress-system
  resourceVersion: "1"
spec:
  gatewayClassName: higress-gateway
  listeners:
  - allowedRoutes:
      namespaces:
        from: All
    name: http
    port: 80
    protocol: HTTP
status: {}
