apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: higress-http-resolver-cluster
  namespace: higress-system
spec:
  configPatches:
    - applyTo: CLUSTER
      match:
        context: GATEWAY
      patch:
        operation: ADD
        value:
          name: "outbound|8889||higress-controller.higress-system.svc.cluster.local"
          type: STATIC
          connect_timeout: 5s
          lb_policy: ROUND_ROBIN
          load_assignment:
            cluster_name: "outbound|8889||higress-controller.higress-system.svc.cluster.local"
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: 127.0.0.1
                          port_value: 8889